<h1>Compliance test, removeClass</h1>
<p>
Here we test removeClass alternatives which are able to remove <b>multiple</b> class names in one go. Candidates are measured against jQuery result. If you want to see the test of alternatives which only allows removing one class name at the time, go <a href="../removeclass/">here</a>
<!--All candidates except current implementation on youmightnotneedjquery.com was authored by <a href="https://github.com/rosell-dk/">Bjørn Rosell</a>-->
</p>

